### ISSUE TITLE
Production Build not working for me

### ISSUE THREAD

**Issue by sigpoggy** [lukeandersen/react-starter#57]
The npm run dev works fine for me.

When I run npm run build it does create the dist folder and add what appears to be the right files.

In vscode if I run the GoLive server I get the following errors:

**Refused to apply style from 'http://127.0.0.1:5500/main.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.html:49

:5500/assets/apple-icon.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)**

When I open the index.html file with my browser i get:

**Failed to load resource: net::ERR_FILE_NOT_FOUND    main.css:1 
Failed to load resource: net::ERR_FILE_NOT_FOUND    bundle.js:1 
Failed to load resource: net::ERR_FILE_NOT_FOUND    /assets/apple-icon.png:1**

There seems to be at least two problems:
1. the main.css link does not specify type="text/css"
2. the links to the files start with /

The index.html file:

`<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <title>React Starter</title>
        <meta name="description" content="React Starter" />
        <meta name="keywords" content="React,Starter" />
        <meta name="author" content="Person Name" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="apple-touch-icon" href="/assets/apple-icon.png" />
        <link rel="shortcut icon" href="/assets/apple-icon.png" type="image/x-icon" />
        
        
    <link href="/main.css" rel="stylesheet"></head>
    <body>
        <div id="app"></div>
    <script type="text/javascript" src="/bundle.js"></script></body>
</html>`

**Comment by lukeandersen** [comment]
Hey @sigpoggy, the current build requires a server to render the site. When you run `npm run build` it copies a server.js file that can run the site.

After you build out the dist, `cd dist` and then run `node server.js` and the site will run at `http://localhost:9001`

Let me know if you still have issues.
