### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sigpoggy** [lukeandersen/react-starter#58]
Can you add a static site production build?
I don't know how to configure this on my own.

**Comment by lukeandersen** [comment]
Hi @sigpoggy, unfortunately, this isn't something I'm looking to do with the repo as there are quite a few good solutions already. Mainly [GatsbyJS](https://www.gatsbyjs.org/) & [create-react-app](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app)

If I was to make the site static I would basically be making it more like `create-react-app`, the main issue with going static is as you mentioned earlier, the relative paths to assets between development and build which they solve using a `public` directory that both environments share.

The second issue is the router, I'm pretty sure I'd have to change the router options to a hash-based router as it's not being rendered by a server.

This is all possible with this codebase but the two I've mentioned above already do a much better job.

**Comment by sigpoggy** [comment]
Ok, thanks for your response.
